<a href="https://colab.research.google.com/github/Lotfullah21/Deep-Learning/blob/main/Activation_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## Softmax Function
In both softmax regression and neural networks with Softmax outputs, N outputs are generated and one output is selected as the predicted category. In both cases a vector $\mathbf{z}$ is generated by a linear function which is applied to a softmax function. The softmax function converts $\mathbf{z}$  into a probability distribution as described below. After applying softmax, each output will be between 0 and 1 and the outputs will add to 1, so that they can be interpreted as probabilities. The larger inputs  will correspond to larger output probabilities.


The softmax function can be written:
$$a_j = \frac{e^{z_j}}{ \sum_{k=1}^{N}{e^{z_k} }} \tag{1}$$
The output $\mathbf{a}$ is a vector of length N, so for softmax regression, you could also write:
\begin{align}
\mathbf{a}(x) =
\begin{bmatrix}
P(y = 1 | \mathbf{x}; \mathbf{w},b) \\
\vdots \\
P(y = N | \mathbf{x}; \mathbf{w},b)
\end{bmatrix}
=
\frac{1}{ \sum_{k=1}^{N}{e^{z_k} }}
\begin{bmatrix}
e^{z_1} \\
\vdots \\
e^{z_{N}} \\
\end{bmatrix} \tag{2}
\end{align}


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from IPython.display import display,Markdown, Latex
from sklearn.datasets import make_blobs
from matplotlib.widgets import Slider

In [10]:
def softmax_fn(x):
  ez = np.exp(x)
  az = ez/ np.sum(ez)
  return ez

### Lets make a dataset

In [11]:
centers = [[-3,2],[4,1],[9,4],[5,3]]
X_train, y_train = make_blobs(n_samples = 20000, centers = centers, cluster_std = 1.0, random_state = 20)

In [15]:
model = Sequential([
    Dense(45, activation = "relu"),
    Dense(30, activation = "relu"),
    Dense(10, activation = "relu"),
    Dense(4, activation = "softmax")
])

model.compile(loss = tf.keras.losses.SparseCategoricalCrossentropy(),
              optimizer = tf.keras.optimizers.Adam(0.001)
              )

model.fit(X_train , y_train, epochs = 10)

Epoch 1/10
625/625 [==============================] - 2s 2ms/step - loss: 0.5175
Epoch 2/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1945
Epoch 3/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1878
Epoch 4/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1837
Epoch 5/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1850
Epoch 6/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1848
Epoch 7/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1829
Epoch 8/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1837
Epoch 9/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1828
Epoch 10/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1820


here , the lastlayer (output) is a vector of probabilities

In [21]:
prediction = model.predict(X_train)
print("the prediction for first output is", prediction[0])
print("the largest value", np.max(prediction[0]), "the smallest value",np.min(prediction[0]))
print("the ouput with largest probablility is", np.max(prediction[0]))
print("the largest value", np.max(prediction), "the smallest value",np.min(prediction))

the prediction for first output is [9.737790e-06 9.312184e-01 6.402269e-07 6.877116e-02]
the largest value 0.9312184 the smallest value 6.402269e-07
the ouput with largest probablility is 0.9312184
the largest value 1.0 the smallest value 4.0749258e-25


## Prefered modlel 
when dealing with small values and especially if we put them into the exponential form , the round of matters.

for example , X1 = 2/2000 = 0.00020000
and X = (1 + 1/1000)  - (1 - 1/1000)  = 0.00019999978 , if we sum the fraction that should lead us to X1 , but the values changes and the 2nd is more accurate numerically, if we calculate them, 

Hence , the 2nd way is preferred way of doing so, and in the loss function we will put the fraction rather than pre computed value.
the way to implement this in tensorflow, we will use linear instead of softmax in the output layer, and directly feed the z's : 
**( z = w * x = b )** to the model.
for example we had  **a = softmax(z)**.

we add from_logits=True in the loss function.

In [24]:
preferred_model = Sequential(
    [ 
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'linear')   
    ]
)
preferred_model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),  
    optimizer=tf.keras.optimizers.Adam(0.001),
)

preferred_model.fit(
    X_train,y_train,
    epochs=10
)

Epoch 1/10
625/625 [==============================] - 2s 2ms/step - loss: 0.5760
Epoch 2/10
625/625 [==============================] - 1s 2ms/step - loss: 0.2329
Epoch 3/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1925
Epoch 4/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1857
Epoch 5/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1828
Epoch 6/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1821
Epoch 7/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1814
Epoch 8/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1810
Epoch 9/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1811
Epoch 10/10
625/625 [==============================] - 1s 2ms/step - loss: 0.1802


## Output
Now , we will see the difference in the output, from the previous model, here the ouptuts are not in probability range, the are from positive to negaetive values.

In [26]:
p_preferred = preferred_model.predict(X_train)
print(f"two example output vectors:\n {p_preferred[:1]}")
print("largest value", np.max(p_preferred), "small|est value", np.min(p_preferred))

two example output vectors:
 [[-4.7439165  5.769028  -6.7612715  3.2307675]]
largest value 23.906492 small|est value -53.579815


if we need the output to be in probability format, we need to feed them through a softmax function.

In [27]:
sm_preferred = tf.nn.softmax(p_preferred).numpy()
print(f"two example output vectors:\n {sm_preferred[:2]}")
print("largest value", np.max(sm_preferred), "smallest value", np.min(sm_preferred))

two example output vectors:
 [[2.5191302e-05 9.2675447e-01 3.3506146e-06 7.3217027e-02]
 [9.9999881e-01 7.3573369e-07 2.7264979e-19 4.7177386e-07]]
largest value 1.0 smallest value 2.4570135e-34


if we don't want to use softmax , we can loop through and using np.argmax(), find the largest values and assign them 

In [28]:
for i in range(5):
    print( f"{p_preferred[i]}, category: {np.argmax(p_preferred[i])}")

[-4.7439165  5.769028  -6.7612715  3.2307675], category: 1
[ 11.165252   -2.9571445 -31.580847   -3.4015129], category: 0
[-4.509475   4.421056  -9.387452   3.2539837], category: 1
[ 14.087609  -5.33493  -33.198704  -5.889166], category: 0
[ -2.8592422   6.43744   -12.837223    3.1675327], category: 1


## SparseCategorialCrossentropy or CategoricalCrossEntropy
Tensorflow has two potential formats for target values and the selection of the loss defines which is expected.
- SparseCategorialCrossentropy: expects the target to be an integer corresponding to the index. For example, if there are 10 potential target values, y would be between 0 and 9. 
- CategoricalCrossEntropy: Expects the target value of an example to be one-hot encoded where the value at the target index is 1 while the other N-1 entries are zero. An example with 10 potential target values, where the target is 2 would be [0,0,1,0,0,0,0,0,0,0].


Source : https://www.coursera.org/learn/advanced-learning-algorithms/ungradedLab/7oaSL/softmax/lab?path=%2Fnotebooks%2FC2_W2_SoftMax.ipynb